Isle printer
wellesley-prog-sys/wasmtime pull request #23
Opened 2024-07-15 19:14 UTC by megdugan

First version of code - needs feedback.

2024-07-15 19:28 UTC, avanhatt requested changes

2024-07-15 19:28 UTC, avanhatt commented on cranelift/isle/isle/src/printer.rs
> +                    parts.push_str(&format!("{}", prio));
Let's use `x.to_string();` instead

2024-07-15 19:28 UTC, avanhatt commented on cranelift/isle/isle/src/printer.rs
> +                parts.extend(&r.iflets.iter().map(|il| il.to_doc()));
Try using `join` for now.

2024-07-15 19:28 UTC, avanhatt commented on cranelift/isle/isle/src/printer.rs
> +                return parts
`sexp` means we need to have open paren before `(` and closed paren after `)`.

2024-07-15 19:28 UTC, avanhatt commented on cranelift/isle/isle/src/printer.rs
> +            Expr::ConstInt { val, .. } => format!("{}", val),
Also use `to_string()`

2024-07-15 19:28 UTC, avanhatt commented on cranelift/isle/isle/src/printer.rs
> +        format!("{}{}{}", &self.var.to_doc(), &self.ty.to_doc(), &self.val.to_doc())
Conceptually, should be:
```
format!("({} {} {})", &self.var.to_doc(), &self.ty.to_doc(), &self.val.to_doc())
```

We'll likely want to represent sexprs separately later, but for now this works

2024-07-16 17:58 UTC, megdugan commented on cranelift/isle/isle/src/printer.rs
> +                    // join is not defined for Maps
Still having trouble adding the Map to the string (most of my errors are relating to this problem)

2025-04-23 18:53 UTC, closed without merging